name: Acceptance Tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1-5" # Weekdays at 06:00 UTC

permissions:
  contents: read

jobs:
  acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    environment: acceptance
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - run: JAMFSCHOOL_ACC=1 go test -v -cover -count=1 -tags acceptance -timeout 120m -p=1 ./...
        env:
          JAMFSCHOOL_URL: ${{ secrets.JAMFSCHOOL_URL }}
          JAMFSCHOOL_NETWORK_ID: ${{ secrets.JAMFSCHOOL_NETWORK_ID }}
          JAMFSCHOOL_API_KEY: ${{ secrets.JAMFSCHOOL_API_KEY }}
